apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tailor.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  FRAGMENT_MOBILE: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-mobile
  FRAGMENT_HEADER: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-header
  FRAGMENT_FOOTER: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-footer
  FRAGMENT_SALES: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-sales
  FRAGMENT_SELFCARE: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-selfcare
  FRAGMENT_CHAT: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-chat
  FRAGMENT_COMMON: https://mobile.beta-c-onboarding-eu-north-1.aws.c.dk/fragment-common
  PORT: '8080'